services:
  backend:
    build:
      context: ./Back-end/country-ticker-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DB=countrytickerappdb
      - MYSQL_USER=userdb6
      - MYSQL_PASSWORD=12345
    depends_on:
      - db

  frontend:
    build:
      context: ./Front-end/country-travel-tracker
      dockerfile: Dockerfile
    ports:
      - "4200:4000" # Map port 4000 in the container to port 4200 on the host

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: countrytickerappdb
      MYSQL_USER: userdb6
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: